In [44]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, cross_val_score

In [10]:
digits = load_digits()

In [11]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [21]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size =0.3)

In [22]:
lr = LogisticRegression(max_iter = 1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

In [23]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

In [24]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9796296296296296

Need to run the above models multiple times as the accuracy might change in different runs

In [28]:
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [54]:
#example
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [31]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [36]:
get_score(LogisticRegression(max_iter = 1000), X_train, X_test, y_train, y_test)

0.9611111111111111

Stratified KFold divides each of classification category in a uniform way

In [39]:
folds = StratifiedKFold(n_splits = 3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [40]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter = 1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 40), X_train, X_test, y_train, y_test))

In [41]:
scores_lr

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [42]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [43]:
scores_rf

[0.9198664440734557, 0.9515859766277128, 0.9332220367278798]

Instead of manually computing scores for each split, there is method 'cross_val_score' which compute it automatically.

In [47]:
cross_val_score(LogisticRegression(max_iter = 1000), digits.data, digits.target)
#this method performed the same thing as given in the above for loop

array([0.92222222, 0.86944444, 0.94428969, 0.93871866, 0.89693593])

In [48]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [49]:
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target)

array([0.92222222, 0.91111111, 0.95264624, 0.96657382, 0.91364903])