In [25]:
import cv2
import numpy as np

In [26]:
img = cv2.imread("assets/image.JPG")
img = cv2.resize(img, (0,0), fx = 1.5, fy=1.5)

In [27]:
#convert to greyscale for better algo work
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [28]:
corners = cv2.goodFeaturesToTrack(gray, 6, 0.01, 5)#6 best corners will be returned with 0.01 confidence with minimum euclidean distance of 5
print(corners)

[[[159. 261.]]

 [[188. 105.]]

 [[119. 236.]]

 [[230. 111.]]

 [[253. 253.]]

 [[142. 190.]]]


In [29]:
corners = np.int0(corners)
corners

C:\Users\davis\AppData\Local\Temp\ipykernel_7968\1143071229.py:1: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  corners = np.int0(corners)


array([[[159, 261]],

       [[188, 105]],

       [[119, 236]],

       [[230, 111]],

       [[253, 253]],

       [[142, 190]]], dtype=int64)

In [30]:
for corner in corners:
    x,y = corner.ravel() #[[x,y]] -> [x,y]
    cv2.circle(img, (x,y), 5, (255,0,0), -1)

In [31]:
#To draw lines between corner points
for i in range(len(corners)):
    for j in range(i+1, len(corners)):
        corner1 = tuple(corners[i][0])
        corner2 = tuple(corners[j][0])
        color = tuple(map(lambda x: int(x), np.random.randint(0,255, size =3)))#random colour generation
        cv2.line(img, corner1, corner2, color, 1)

In [32]:
cv2.imshow("Frame", img)
cv2.waitKey(0)
cv2.destroyAllWindows()