In [7]:
import cv2
import random

In [2]:
img = cv2.imread("assets/image.JPG", -1)

In [3]:
print(img) #loads the image into a numpy array

[[[152 122 127]
  [142 112 117]
  [169 139 144]
  ...
  [119  89  94]
  [119  89  94]
  [118  88  93]]

 [[155 125 130]
  [167 137 142]
  [167 137 142]
  ...
  [116  86  91]
  [114  84  89]
  [112  82  87]]

 [[170 140 145]
  [167 137 142]
  [145 115 120]
  ...
  [127  97 102]
  [126  96 101]
  [125  95 100]]

 ...

 [[147 120 129]
  [144 117 126]
  [141 114 123]
  ...
  [117  91  97]
  [116  90  96]
  [114  88  94]]

 [[148 121 130]
  [145 118 127]
  [142 115 124]
  ...
  [117  91  97]
  [114  88  94]
  [111  85  91]]

 [[149 122 131]
  [146 119 128]
  [142 115 124]
  ...
  [115  89  95]
  [111  85  91]
  [107  81  87]]]


In [4]:
print(img.shape)

(256, 256, 3)


In [6]:
print(img[0][45:400])

[[161 131 136]
 [151 121 126]
 [145 115 120]
 [152 122 127]
 [147 117 122]
 [148 118 123]
 [154 124 129]
 [146 116 121]
 [162 132 137]
 [140 110 115]
 [169 139 144]
 [149 119 124]
 [158 128 133]
 [143 113 118]
 [138 108 113]
 [155 125 130]
 [146 116 121]
 [131 101 106]
 [148 118 123]
 [156 126 131]
 [164 134 139]
 [166 136 141]
 [148 118 123]
 [164 134 139]
 [131 101 106]
 [129  99 104]
 [148 118 123]
 [131 101 106]
 [154 124 129]
 [152 122 127]
 [140 110 115]
 [144 114 119]
 [139 109 114]
 [132 102 107]
 [139 109 114]
 [136 106 111]
 [139 109 114]
 [141 111 116]
 [157 127 132]
 [137 107 112]
 [145 115 120]
 [145 115 120]
 [153 123 128]
 [144 114 119]
 [153 123 128]
 [155 125 130]
 [147 117 122]
 [143 113 118]
 [147 117 122]
 [152 122 127]
 [151 121 126]
 [146 116 121]
 [152 122 127]
 [150 120 125]
 [155 125 130]
 [139 109 114]
 [157 127 132]
 [150 120 125]
 [138 108 113]
 [158 128 133]
 [154 124 129]
 [147 117 122]
 [143 113 118]
 [149 119 124]
 [154 124 129]
 [147 117 122]
 [134 104 

In [ ]:
#modifies the top 100 rows of the image by replacing every pixel with a random color
for i in range(100):
    for j in range(img.shape[1]):
        img[i][j] = [random.randint(0,255), random.randint(0,255), random.randint(0,255)]

In [10]:
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

##Copy part of the image

In [14]:
tag = img[100:178, 60:97]

In [15]:
img[150:228, 100:137] = tag

In [16]:
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()